apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
# Base 64 encoding can be done :  echo -n <serret name> | base64 - mongouser/mongopassword
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
